/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csx55.overlay;

public class App {

    public static void main(String[] args) {

        System.out.println("APP CLASS");

    }
}
