/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csx55.overlay;

import csx55.overlay.node.Registry;

public class App {

    public static void main(String[] args) {

        Registry reg = new Registry();
        reg.registerStart();

    }
}
